branch-defaults:
  aws-ebconfig:
    environment: letsgifton-dev9
  master:
    environment: gifton-staging
global:
  application_name: letsgifton
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2016.09 v2.3.1 running Ruby 2.3 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
