branch-defaults:
  aws-config:
    environment: letsgifton-beta
    group_suffix: null
  aws-es-config:
    environment: letsgifton-beta
  components:
    environment: letsgifton-beta
  daily_email_cronjob:
    environment: letsgifton-beta
  resolve_log_errors:
    environment: letsgifton-beta
global:
  application_name: letsgifton
  branch: null
  default_ec2_keyname: letsgifton-eb-key
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
